name: CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Deploy Staging
        if: github.ref == 'refs/heads/develop'
        run: npm run deploy:staging

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: npm run deploy:prod
